INSERT INTO subjects (title, description, display_order) VALUES
('JavaScript Fundamentals', 'Learn the basics of JavaScript programming', 1),
('React.js Mastery', 'Master React.js from beginner to advanced', 2),
('Node.js Backend', 'Build scalable backend applications with Node.js', 3),
('Python Programming', 'Complete Python course from basics to advanced', 4),
('Machine Learning Basics', 'Introduction to machine learning and AI', 5),
('Web Design Fundamentals', 'Learn HTML, CSS, and responsive design', 6),
('Database Management', 'Master SQL and database design', 7),
('Cloud Computing AWS', 'Learn Amazon Web Services from scratch', 8),
('Mobile App Development', 'Build iOS and Android apps with React Native', 9),
('Cybersecurity Essentials', 'Learn ethical hacking and security', 10),
('Data Science with Python', 'Analyze data and create visualizations', 11),
('DevOps Engineering', 'Master CI/CD, Docker, and Kubernetes', 12),
('UI/UX Design', 'Create beautiful user interfaces', 13),
('Blockchain Development', 'Build decentralized applications', 14),
('Game Development Unity', 'Create games with Unity engine', 15);

INSERT INTO sections (subject_id, title, display_order) VALUES
(1, 'Introduction to JavaScript', 1),(1, 'Advanced JavaScript', 2),(1, 'JavaScript Projects', 3),
(2, 'React Basics', 1),(2, 'State Management', 2),(2, 'Advanced React', 3),
(3, 'Node.js Fundamentals', 1),(3, 'Express.js Framework', 2),(3, 'Database Integration', 3),
(4, 'Python Basics', 1),(4, 'Object-Oriented Python', 2),(4, 'Python Projects', 3),
(5, 'ML Introduction', 1),(5, 'Supervised Learning', 2),(5, 'Deep Learning', 3),
(6, 'HTML & CSS Basics', 1),(6, 'Responsive Design', 2),(6, 'Modern CSS', 3),
(7, 'SQL Fundamentals', 1),(7, 'Database Design', 2),(7, 'Advanced Queries', 3),
(8, 'AWS Basics', 1),(8, 'EC2 and S3', 2),(8, 'AWS Architecture', 3),
(9, 'React Native Basics', 1),(9, 'Mobile UI Design', 2),(9, 'App Deployment', 3),
(10, 'Security Fundamentals', 1),(10, 'Ethical Hacking', 2),(10, 'Network Security', 3),
(11, 'Data Analysis', 1),(11, 'Data Visualization', 2),(11, 'Machine Learning', 3),
(12, 'DevOps Basics', 1),(12, 'Docker & Kubernetes', 2),(12, 'CI/CD Pipelines', 3),
(13, 'Design Principles', 1),(13, 'Figma Mastery', 2),(13, 'User Research', 3),
(14, 'Blockchain Basics', 1),(14, 'Smart Contracts', 2),(14, 'DApp Development', 3),
(15, 'Unity Basics', 1),(15, 'Game Mechanics', 2),(15, '3D Game Development', 3);

INSERT INTO videos (section_id, title, youtube_id, duration, concept, display_order) VALUES
(1,'JavaScript Crash Course for Beginners','PkZNo7MFNFg',4980,'Full JavaScript crash course covering all fundamentals from scratch by Traversy Media.',1),(1,'JavaScript Variables & Data Types','edlFjlzxkSI',780,'Learn var, let, const and all JavaScript data types with examples.',2),(1,'JavaScript Functions Tutorial','N8ap4k_1QEQ',2940,'Master function declarations, expressions, arrow functions and parameters.',3),
(2,'JavaScript Higher Order Functions','rRgD1yVwIvE',1560,'Deep dive into map, filter, reduce and higher-order functions.',1),(2,'JavaScript Closures Explained','3a0I8ICR1Vg',660,'Understand closures, lexical scope and practical use cases.',2),(2,'Async JavaScript - Callbacks, Promises, Async Await','PoRJizFvM7s',2520,'Learn callbacks, promises and async/await for asynchronous operations.',3),
(3,'Build a Calculator with JavaScript','j59qQ7YWLxw',2640,'Build a fully functional calculator using HTML CSS and JavaScript DOM.',1),(3,'JavaScript Todo List App','G0jO8kUrg-I',3120,'Build a complete todo app with add, delete, filter and localStorage.',2),(3,'Build a Weather App with JavaScript','MIYQR-Ybrn4',3600,'Create a weather app using OpenWeather API and JavaScript fetch.',3),
(4,'What is React?','Tn6-PIqc4UM',600,'Introduction to React framework and its core concepts like components and virtual DOM.',1),(4,'JSX Syntax','DLX62G4lc44',540,'Learn JSX syntax and how to render HTML-like code in JavaScript.',2),(4,'Components','Y2hgEGPzTZY',720,'Understand functional and class components and component hierarchy.',3),
(5,'useState Hook','O6P86uwfdR0',660,'Master the useState hook for managing component state in React.',1),(5,'useEffect Hook','0ZJgIjIuY7U',780,'Learn useEffect for side effects, dependencies, and cleanup functions.',2),(5,'Context API','HYKDUF8X3qI',840,'Share state across components using Context API without prop drilling.',3),
(6,'Custom Hooks','J-g9ZJha8FE',720,'Create reusable custom hooks to encapsulate component logic.',1),(6,'Performance','uojLJFt9SzY',900,'Optimize React apps using memoization, code splitting, and lazy loading.',2),(6,'React Router','Ul3y1LXxzdU',840,'Implement client-side routing using React Router for multi-page applications.',3),
(7,'Node.js Intro','TlB_eWDSMt4',600,'Learn what Node.js is and how to run JavaScript on the server side.',1),(7,'Node Modules','xHLd36QoS4k',540,'Understand the module system and how to create and use modules.',2),(7,'File System','U57kU311-nE',720,'Work with the file system to read, write, and manage files in Node.js.',3),
(8,'Express Basics','L72fhGm1tfE',660,'Introduction to Express.js framework for building web applications.',1),(8,'Routing','lY6icfhap2o',780,'Create routes to handle different HTTP methods and URL paths.',2),(8,'REST API','pKd0Rpw7O48',900,'Build RESTful APIs with proper endpoints and response handling.',3),
(9,'MySQL Integration','EN6Dx22cPRI',840,'Connect Node.js applications to MySQL database and perform CRUD operations.',1),(9,'MongoDB','-56x56UppqQ',900,'Use MongoDB as NoSQL database with Node.js using mongoose ORM.',2),(9,'Best Practices','W2Z7fbCLSTw',720,'Follow best practices for security, error handling, and code organization.',3),
(10,'Python Introduction','kqtD5dpn9C8',600,'Get started with Python, understand syntax and basic concepts.',1),(10,'Python Variables','YYXdXT2l-Gg',540,'Learn about data types, variable assignment, and type conversion.',2),(10,'Python Functions','NSbOtYzIQI0',720,'Create and use functions, understand parameters, return values, and scope.',3),
(11,'Classes and Objects','ZDa-Z5JzLYM',660,'Understand object-oriented programming with classes and object creation.',1),(11,'Inheritance','RSl87lqOXDE',780,'Learn inheritance hierarchies and how to extend classes.',2),(11,'Polymorphism','wfcWRAxRVBA',840,'Understand polymorphism and method overriding in OOP.',3),
(12,'Web Scraper','XQgXKtPSzUI',720,'Create web scrapers using BeautifulSoup and Requests library.',1),(12,'Data Analysis','vmEHCJofslg',900,'Analyze data using Pandas and perform data manipulation operations.',2),(12,'Automation','PXMJ6FS7llk',840,'Automate tasks and create scripts for everyday automation.',3),
(13,'ML Introduction','ukzFI9rgwfU',600,'Introduction to Machine Learning concepts and types of learning.',1),(13,'ML Algorithms','E0W1ZZYIV8o',540,'Learn various machine learning algorithms and when to use them.',2),(13,'Data Preprocessing','Gv9_4yMHFhI',720,'Prepare and clean data for machine learning models.',3),
(14,'Linear Regression','nk2CQITm_eo',660,'Understand and implement linear regression for prediction tasks.',1),(14,'Classification','vsWrXfO3wWw',780,'Learn classification algorithms like logistic regression and decision trees.',2),(14,'Decision Trees','RmajweUFKvM',840,'Master decision tree algorithms and ensemble methods.',3),
(15,'Neural Networks','aircAruvnKk',720,'Introduction to neural networks and deep learning concepts.',1),(15,'CNN','YRhxdVk_sIs',900,'Build Convolutional Neural Networks for image classification.',2),(15,'RNN','LHXXI4-IEns',840,'Create Recurrent Neural Networks for sequential data processing.',3),
(16,'HTML Basics','qz0aGYrrlhU',600,'Learn HTML structure, tags, and semantic markup.',1),(16,'CSS Fundamentals','yfoY53QXEnI',720,'Master CSS selectors, properties, and styling techniques.',2),(16,'HTML Forms','fNcJuPIZ2WE',540,'Create and validate HTML forms for user input.',3),
(17,'Flexbox Layout','JJSoEo8JSnc',660,'Learn Flexbox for flexible and responsive layouts.',1),(17,'CSS Grid','jV8B24rSN5o',780,'Master CSS Grid for complex layout designs.',2),(17,'Media Queries','yU7jJ3NbPdA',840,'Create responsive designs with CSS media queries.',3),
(18,'CSS Variables','oZPR_78wCnY',720,'Use CSS custom properties to manage themes and dynamic styling.',1),(18,'CSS Animations','zHUpx90NerM',900,'Create smooth animations and transitions with CSS.',2),(18,'Sass/SCSS','_a5j7KoflTs',840,'Use Sass preprocessor for better CSS organization.',3),
(19,'SQL Introduction','HXV3zeQKqGY',600,'Learn SQL basics and relational database concepts.',1),(19,'SELECT Queries','9Pzj7Aj25lw',540,'Master SELECT statements for querying data.',2),(19,'WHERE Clause','YufocuHbYZo',720,'Filter and retrieve specific data using WHERE conditions.',3),
(20,'Database Design','ztHopE5Wnpc',660,'Learn database design principles and schema creation.',1),(20,'Normalization','GFQaEYEc8_8',780,'Understand database normalization to eliminate redundancy.',2),(20,'ER Diagrams','QpdhBUYk7Kk',840,'Create Entity-Relationship diagrams for database planning.',3),
(21,'JOINs','9yeOJ0ZMUYw',720,'Combine data from multiple tables using various JOIN operations.',1),(21,'Subqueries','nJIEIzF7tDw',900,'Use subqueries for complex data retrieval operations.',2),(21,'Indexes','fsG1XaZEa78',840,'Create and optimize database indexes for performance.',3),
(22,'AWS Introduction','JIbIYCM48to',600,'Introduction to Amazon Web Services and cloud computing basics.',1),(22,'AWS Account Setup','XhW17g73fvY',540,'Create and configure AWS account with proper IAM setup.',2),(22,'IAM Basics','iS9ZjJ2Bnlg',720,'Manage users and permissions using AWS Identity Access Management.',3),
(23,'EC2 Instances','iHX-jtKIVNA',660,'Launch and manage virtual servers using EC2.',1),(23,'S3 Storage','tfU0JEZjcsg',780,'Use S3 for scalable and reliable object storage.',2),(23,'EBS Volumes','S0NB3RRgFSs',840,'Manage persistent block storage with EBS volumes.',3),
(24,'VPC Networking','fpxDGU2KdkA',720,'Create and configure Virtual Private Clouds for network isolation.',1),(24,'Load Balancers','VIgAT7vjol8',900,'Distribute traffic using Load Balancers for high availability.',2),(24,'Auto Scaling','SZyOlBmFMoE',840,'Automatically scale resources based on demand.',3),
(25,'React Native Intro','ur6I5m2nTvk',600,'Introduction to React Native for cross-platform mobile development.',1),(25,'Setup Environment','ANdSdIlgsEw',540,'Set up development environment for React Native projects.',2),(25,'First App','obH0Po_RdWk',720,'Create your first React Native application.',3),
(26,'Mobile Components','qSRrxpdMpVc',660,'Learn React Native components and their properties.',1),(26,'Navigation','nQVCkqvU1uE',780,'Implement navigation between screens in mobile apps.',2),(26,'Styling','GrfOsWUiwrw',840,'Style React Native components with StyleSheet API.',3),
(27,'App Store Deploy','LE4Mgkrf7Sk',720,'Deploy applications to Apple App Store.',1),(27,'Play Store Deploy','oBWBDaqNuws',900,'Deploy applications to Google Play Store.',2),(27,'App Testing','CfdGIZkYwEU',840,'Test mobile applications for quality and performance.',3),
(28,'Security Basics','inWWhr5tnEA',600,'Understand fundamental security concepts and threats.',1),(28,'Encryption','AQDCe585Lnc',540,'Learn encryption methods for data protection.',2),(28,'Authentication','j8Tywg0H-xQ',720,'Implement secure authentication mechanisms.',3),
(29,'Ethical Hacking','dz7Ntp7KQGA',660,'Learn ethical hacking techniques and methodology.',1),(29,'Penetration Testing','3Kq1MIfTWCE',780,'Perform authorized penetration testing on systems.',2),(29,'Vulnerability Scan','lc7scxvKQOo',840,'Scan and identify vulnerabilities in applications.',3),
(30,'Network Security','kBzbKUirOFk',720,'Protect networks from cyber attacks and threats.',1),(30,'Firewall Config','kDEX1HXybrU',900,'Configure firewalls for network protection.',2),(30,'Security Tools','qPEA6J9pjG8',840,'Use security tools for monitoring and analysis.',3),
(31,'Data Science Intro','ua-CiDNNj30',600,'Introduction to data science workflows and techniques.',1),(31,'Pandas Basics','vmEHCJofslg',540,'Learn data manipulation with Pandas library.',2),(31,'NumPy Arrays','QUT1VHiLmmI',720,'Work with numerical arrays using NumPy.',3),
(32,'Matplotlib','3Xc3CA655Y4',660,'Create static visualizations with Matplotlib.',1),(32,'Seaborn','6GUZXDef2U0',780,'Build statistical visualizations with Seaborn.',2),(32,'Plotly','GGL6U0k8WYA',840,'Create interactive visualizations with Plotly.',3),
(33,'Scikit-learn','0Lt9w-BxKFQ',720,'Use scikit-learn for machine learning tasks.',1),(33,'Model Training','i_LwzRVP7bg',900,'Train machine learning models on datasets.',2),(33,'Model Evaluation','Kdsp6soqA7o',840,'Evaluate model performance with metrics.',3),
(34,'DevOps Introduction','Xrgk023l4lI',600,'Introduction to DevOps principles and practices.',1),(34,'CI/CD Basics','scEDHsr3APg',540,'Learn Continuous Integration and Continuous Deployment.',2),(34,'Git Workflow','HVsySz-h9r4',720,'Master Git workflows for version control.',3),
(35,'Docker Basics','fqMOX6JJhGo',660,'Containerize applications using Docker.',1),(35,'Docker Compose','Qw9zlE3t8Ko',780,'Orchestrate multiple containers with Docker Compose.',2),(35,'Kubernetes Intro','X48VuDVv0do',840,'Manage containers at scale with Kubernetes.',3),
(36,'Jenkins Pipeline','pMO26j2OUME',720,'Build CI/CD pipelines using Jenkins automation.',1),(36,'GitHub Actions','R8_veQiYBjI',900,'Automate workflows with GitHub Actions.',2),(36,'Terraform','l5k1ai_GBDE',840,'Infrastructure as Code with Terraform.',3),
(37,'Design Principles','a5KYlHNKQB8',600,'Learn fundamental principles of design.',1),(37,'Color Theory','_2LLXnUdUIc',540,'Understand color theory and color palettes.',2),(37,'Typography','sByzHoiYFX0',720,'Master typography for effective communication.',3),
(38,'Figma Basics','FTFaQWZBqQ8',660,'Design interfaces using Figma design tool.',1),(38,'Prototyping','lTIeZ2ahEkQ',780,'Create interactive prototypes in Figma.',2),(38,'Design Systems','Dtd40cHQQlk',840,'Build scalable design systems with Figma.',3),
(39,'User Research','Ovj4hFxko7c',720,'Conduct user research for design insights.',1),(39,'Usability Testing','Z5gqrow7wNs',900,'Test designs with real users for validation.',2),(39,'UX Strategy','gUja_9QLKR4',840,'Develop UX strategies for product success.',3),
(40,'Blockchain Basics','SSo_EIwHSd4',600,'Introduction to blockchain technology.',1),(40,'Cryptocurrency','1YyAzVmP9xQ',540,'Understand cryptocurrencies and digital assets.',2),(40,'Bitcoin Explained','bBC-nXj3Ng4',720,'Learn how Bitcoin works and blockchain mechanics.',3),
(41,'Solidity Basics','ipwxYa-F1uY',660,'Learn Solidity language for smart contracts.',1),(41,'Smart Contracts','M576WGiDBdQ',780,'Develop smart contracts on Ethereum.',2),(41,'Ethereum','jxLkbJozKbY',840,'Understanding Ethereum network and protocol.',3),
(42,'Web3.js','u3PtGMRmGA0',720,'Use Web3.js to interact with blockchain.',1),(42,'DApp Development','coQ5dg8wM2o',900,'Build decentralized applications.',2),(42,'NFT Creation','meTpMP0J5E8',840,'Create and deploy NFTs on blockchain.',3),
(43,'Unity Introduction','pwZpJzpE2lQ',600,'Introduction to Unity game development engine.',1),(43,'Unity Interface','IlKaB1etrik',540,'Navigate and understand Unity editor interface.',2),(43,'First Game','j48LtUkZRjU',720,'Create your first game in Unity.',3),
(44,'Game Physics','wB1pcXtEwIs',660,'Implement physics in games using Unity physics engine.',1),(44,'Collision Detection','vFjXKOXdgGo',780,'Detect and handle collisions between game objects.',2),(44,'Player Movement','f473C43s8nE',840,'Implement responsive player character movement.',3),
(45,'3D Modeling','f3Cn0CGytSQ',720,'Create 3D models for game environments.',1),(45,'Game AI','aR6wt5BlE-',900,'Implement artificial intelligence for game characters.',2),(45,'Game Publishing','HlDGSStxuHI',840,'Publish and distribute games on platforms.',3);
